#!/bin/bash

# This contains Orion-related firewall scripts
# which is necessary to route packets correctly
# feel free to go see them!
. /usr/lib/orion-firewall/user-utils

# Exposer un serveur sur le port 80
# route_ip "10.30.1.1" "192.168.1.1" "80"