name: Release

on:
  push:
    tags:        
      - '*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: gem install fpm
    - run: ./build.sh
    - uses: actions/checkout@v4
      with:
        repository: Orion-network-dev/apt-registry
        path: output-apt-repo/
    - run: mkdir -p output-apt-repo/orion-firewall/
    - run: rm output-apt-repo/orion-firewall/*.deb
    - run: cp orion*.deb output-apt-repo/orion-firewall/
    - run: rm -rf output-apt-repo/.git
    - name: Pushes to the apt repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_APT_GITHUB }}
      with:
        source-directory: 'output-apt-repo/'
        destination-github-username: 'Orion-network-dev'
        destination-repository-name: 'apt-registry'
        user-email: 'orion+firewall@mpgn.dev'
        target-branch: main
